"""
MVP: LLM-authored ontology, Jev-filtered.

Illustrates the cascade:
    LLM authors the ontology (expensive, infrequent)
    -> Jev filters / classifies items against it (cheap, high-volume, per item)

The LLM authoring step is simulated (the ontology is hardcoded as the kind of
structured JSON an LLM would produce). Jev classification uses the real
TypeSafe API (POST https://api.typesafe.ai/v1/systemone) if TYPESAFE_API_KEY
is set; otherwise it falls back to a keyword-based mock.

Run:  python mvp_jev_ontology.py
"""

import json
import os
import random
import urllib.request
from collections import Counter

# --------------------------------------------------------------------------- #
# Step 1: Load the LLM-authored ontology
# --------------------------------------------------------------------------- #
# The ontology is generated by an LLM and saved as ontology.json.
# In this project it was authored by Mistral Vibe (an LLM) from the prompt:
#
#   "Create an ontology for customer-support tickets for a SaaS product as
#    JSON. Each class has id, label, definition, and optional children
#    (sub-classes). Aim for 3 levels. Make definitions specific enough that
#    a classifier can distinguish siblings."
#
# The metadata is stored in the _meta key of the JSON file.

ONTOLOGY_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ontology.json")

with open(ONTOLOGY_PATH, "r", encoding="utf-8") as f:
    _ONTOLOGY_FILE = json.load(f)

ONTOLOGY_VERSION = _ONTOLOGY_FILE.get("_meta", {}).get("version", "unknown")
ONTOLOGY = {k: v for k, v in _ONTOLOGY_FILE.items() if k != "_meta"}

# --------------------------------------------------------------------------- #
# Step 2: Jev Choice -- real API call with mock fallback
# --------------------------------------------------------------------------- #
# Calls the TypeSafe Jev API: POST https://api.typesafe.ai/v1/systemone
# Sends the ticket text + the current ontology node's context as state, and a
# Choice question whose criteria are the child class definitions.
#
# Response shape:
#   { "model": "jev-1.13.0",
#     "answers": { "classify": { "type": "choice", "choice": "...",
#                 "confidence": 0.82,
#                 "probabilities": {"opt_a": 0.88, "opt_b": 0.12, ...} } },
#     "usage": { "input_tokens": 349, "output_tokens": 38 } }

API_KEY = os.environ.get("TYPESAFE_API_KEY", "")
ENDPOINT = "https://api.typesafe.ai/v1/systemone"
USE_REAL_JEV = bool(API_KEY)


def jev_choice(item_text, children, parent):
    """Call the real Jev API with a Choice question over the node's children."""
    criteria = {c["id"]: c["definition"] for c in children}
    state = (
        f"Support ticket to classify:\n\"{item_text}\"\n\n"
        f"Ontology context: \"{parent['label']}\" -- {parent['definition']}\n"
        f"Choose the most specific sub-class this ticket belongs to."
    )
    body = {
        "model": "jev-latest",
        "state": state,
        "questions": {
            "classify": {
                "type": "choice",
                "instructions": (
                    f"Which sub-class of \"{parent['label']}\" does this "
                    f"ticket belong to?"
                ),
                "criteria": criteria,
            }
        },
    }
    req = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))

    answer = data["answers"]["classify"]
    return {
        "choice": answer["choice"],
        "confidence": answer["confidence"],
        "distribution": answer["probabilities"],
    }


# --- Mock fallback (keyword-based, same return shape as real Jev) ---------- #

KEYWORDS = {
    "BillingAndPayments":   ["billing", "payment", "refund", "charge", "invoice", "subscription", "plan", "price", "card"],
    "TechnicalAndProduct":   ["bug", "error", "crash", "feature", "integration", "api", "broken", "slow", "lag", "not working"],
    "AccountAndAccess":     ["login", "password", "access", "account", "security", "breach", "locked", "2fa", "sso", "permission"],
    "PaymentFailure":        ["payment", "declined", "failed", "card", "charge", "transaction", "expired", "duplicate"],
    "RefundRequest":         ["refund", "money back", "return", "reimburse"],
    "SubscriptionChange":    ["upgrade", "downgrade", "cancel", "plan", "subscription", "tier", "pause", "annual", "monthly"],
    "InvoiceQuestion":       ["invoice", "charge", "statement", "tax", "bill", "receipt"],
    "BugReport":            ["bug", "crash", "error", "broken", "unexpected", "glitch", "wrong"],
    "FeatureRequest":       ["feature", "request", "wish", "would be nice", "enhancement", "add", "could you"],
    "IntegrationProblem":    ["integration", "api", "connect", "third-party", "webhook", "sync", "stripe", "slack"],
    "PerformanceIssue":     ["slow", "lag", "latency", "timeout", "unresponsive", "loading", "performance"],
    "LoginProblem":          ["login", "sign in", "password", "locked out", "log in", "mfa", "2fa", "session"],
    "AccessRequest":        ["access", "permission", "role", "invite", "grant", "sso", "seat", "team"],
    "SecurityConcern":      ["security", "breach", "phishing", "hacked", "suspicious", "unauthorized", "gdpr", "privacy", "data"],
    "AccountManagement":    ["profile", "email", "delete", "rename", "settings", "update account"],
}


def mock_jev_choice(item_text, children):
    """Return a probability distribution over children, simulating a Jev Choice."""
    text_lower = item_text.lower()
    scores = []
    for child in children:
        kws = KEYWORDS.get(child["id"], [])
        hit = sum(1 for kw in kws if kw in text_lower)
        score = max(hit + random.uniform(0, 0.3), 0.01)
        scores.append(score)

    total = sum(scores)
    probs = {children[i]["id"]: scores[i] / total for i in range(len(children))}
    ranked = sorted(probs.items(), key=lambda x: x[1], reverse=True)
    return {
        "choice": ranked[0][0],
        "confidence": ranked[0][1],
        "distribution": probs,
    }


# --------------------------------------------------------------------------- #
# Step 3: Recursive classifier with beam search and confidence gating
# --------------------------------------------------------------------------- #

def classify_item(item_text, ontology, confidence_threshold=0.7):
    """
    Walk the ontology tree top-down.
    At each node, ask Jev Choice over children. Descend the winner.
    Stop at a leaf or when confidence clears the threshold.
    Returns the path, leaf, and cumulative confidence.
    """
    path = []
    current = ontology
    confidence = 1.0

    while current.get("children"):
        children = current["children"]
        if USE_REAL_JEV:
            result = jev_choice(item_text, children, current)
        else:
            result = mock_jev_choice(item_text, children)

        top_id = result["choice"]
        top_prob = result["confidence"]
        confidence *= top_prob

        child_node = next(c for c in children if c["id"] == top_id)
        path.append({"node": top_id, "confidence": top_prob, "distribution": result["distribution"]})
        current = child_node

    leaf = path[-1]["node"] if path else ontology["id"]
    return {
        "path": path,
        "leaf": leaf,
        "overall_confidence": confidence,
        "ontology_version": ONTOLOGY_VERSION,
    }


# --------------------------------------------------------------------------- #
# Step 4: Sample items to classify
# --------------------------------------------------------------------------- #

SAMPLE_TICKETS = [
    "My credit card was declined when I tried to pay for my subscription.",
    "I want a refund for the charge on my invoice from last month.",
    "The app crashes every time I open the settings page.",
    "I'd love to see a dark mode feature added to the dashboard.",
    "I can't log in - it says my password is incorrect but I'm sure it's right.",
    "I think someone accessed my account without permission, worried about security.",
    "Can I upgrade from the basic plan to the pro plan?",
    "The Stripe integration isn't syncing our orders properly.",
    "The dashboard takes 30 seconds to load ever since the last update.",
    "Can you explain the tax line item on my latest invoice?",
    "I need to change the email address on my account.",
    # Ambiguous ticket (tests the classifier / feedback loop):
    "I was charged twice and now I can't access my account.",
]


# --------------------------------------------------------------------------- #
# Step 5: Run the pipeline + feedback loop
# --------------------------------------------------------------------------- #

def collect_leaves(node, acc):
    if not node.get("children"):
        acc.add(node["id"])
    else:
        for c in node["children"]:
            collect_leaves(c, acc)


def main():
    random.seed(42)
    print("=" * 72)
    print("MVP: LLM-authored ontology -> Jev-filtered")
    print(f"Ontology version: {ONTOLOGY_VERSION}")
    print(f"Jev mode: {'REAL API (jev-latest)' if USE_REAL_JEV else 'MOCK (keyword fallback)'}")
    print("=" * 72)

    # --- Classify each item ---
    results = []
    for ticket in SAMPLE_TICKETS:
        result = classify_item(ticket, ONTOLOGY)
        results.append({"ticket": ticket, **result})

        print(f"\nTicket: {ticket}")
        print(f"  Leaf: {result['leaf']}  (confidence {result['overall_confidence']:.3f})")
        print(f"  Path:")
        for step in result["path"]:
            dist = ", ".join(f"{k}:{v:.2f}" for k, v in
                             sorted(step["distribution"].items(), key=lambda x: x[1], reverse=True))
            print(f"    -> {step['node']} (p={step['confidence']:.3f})  [{dist}]")

    # --- Feedback loop: signals for ontology refinement ---
    print("\n" + "=" * 72)
    print("FEEDBACK LOOP - signals to refine the LLM-authored ontology")
    print("=" * 72)

    leaf_counts = Counter(r["leaf"] for r in results)

    all_leaves = set()
    collect_leaves(ONTOLOGY, all_leaves)

    print("\nItems per leaf class:")
    for leaf_id in sorted(all_leaves):
        count = leaf_counts.get(leaf_id, 0)
        marker = "  <- ZERO TRAFFIC: candidate for removal or merge" if count == 0 else ""
        print(f"  {leaf_id}: {count}{marker}")

    zero_traffic = all_leaves - set(leaf_counts.keys())
    if zero_traffic:
        print(f"\nZero-traffic classes: {sorted(zero_traffic)}")
        print("  -> Re-prompt LLM: 'These classes had zero items. Remove them or")
        print("     merge with a sibling, and re-issue the ontology.'")

    low_conf = [r for r in results if r["overall_confidence"] < 0.5]
    if low_conf:
        print(f"\nLow-confidence items (overall confidence < 0.5):")
        for r in low_conf:
            print(f"  '{r['ticket'][:55]}...' -> {r['leaf']} (conf={r['overall_confidence']:.3f})")
        print("  -> Re-prompt LLM: 'These items were classified with low confidence.")
        print("     Tighten the definitions of the relevant sibling classes.'")

    print(f"\nLow-margin decisions (top-2 probabilities within 0.15):")
    found_margin = False
    for r in results:
        for step in r["path"]:
            ranked = sorted(step["distribution"].items(), key=lambda x: x[1], reverse=True)
            if len(ranked) >= 2 and (ranked[0][1] - ranked[1][1]) < 0.15:
                found_margin = True
                print(f"  '{r['ticket'][:40]}...' at {step['node']}: "
                      f"{ranked[0][0]}({ranked[0][1]:.2f}) vs {ranked[1][0]}({ranked[1][1]:.2f})")
    if not found_margin:
        print("  (none)")

    # Ambiguous item highlight
    ambiguous = [r for r in results if "charged twice" in r["ticket"]]
    if ambiguous:
        print(f"\nAmbiguous ticket (spans two sub-trees):")
        print(f"  '{ambiguous[0]['ticket']}'")
        print(f"  Classified as: {ambiguous[0]['leaf']}")
        print("  -> This is a signal that the ontology may need a multi-label")
        print("     path or a 'compound issue' class. Re-prompt LLM accordingly.")


if __name__ == "__main__":
    main()
